### ISSUE TITLE
Bu003 std::cout 일치하는 피연산자를 찾을 수 없음

### ISSUE THREAD

**Issue by Lcat12345** [Woon-2/cpp-study#117]
![image](https://user-images.githubusercontent.com/62102830/203561947-2776d8ae-1e4b-4e49-b2a5-8620740df20a.png)

std:;cout 자체가 안먹히는 모습입니다.

**Comment by Woon-2** [comment]
여전한가요....   
빨간 줄이 저 위치에 있는 이유를 알 수가 없네요.   

관련 없는 얘기지만 `my_string.inl`이 `include`되지 않은 게 보입니다.   
`헤더 파일`에 `include`해주세요.   
(`#include`를 작성하라는 뜻이 아닙니다.)

**Comment by Woon-2** [comment]
closed by #119
