### ISSUE TITLE
Bu004. mystring.inl에 정의된 operator>> 오류

### ISSUE THREAD

**Issue by Lcat12345** [Woon-2/cpp-study#118]
오류 목록
---
![image](https://user-images.githubusercontent.com/62102830/204012375-3abeee37-6614-4a81-9ad1-59edfef46f70.png)

오류가 뜬 부분 Link
---
https://github.com/Woon-2/cpp-study/blob/68be2e3c214e0e922ef40801f1c6994013d28746/solutions-sprint1-write-cpp-classes/my_string.inl#L1078-L1145

추가 스크린샷
---

- **오류(활성)	E0658	템플릿 정의의 닫는 중괄호를 찾을 수 없습니다.**	

![image](https://user-images.githubusercontent.com/62102830/204012865-eace0adc-0e1c-440b-9d5e-5c9eed40b14c.png)

- **str_max_size가 정의되어 있지만 정의되지 않았다고 뜸**
- **클래스 템플릿 인수를 추론할수 없음**

![image](https://user-images.githubusercontent.com/62102830/204013405-c2566a7b-63b4-4c85-8461-5cc3422ceb56.png)

이하 생략

**Comment by Woon-2** [comment]
closed by #119
