### ISSUE TITLE
BU006 string_benchmark - ret과 std::getline 오류

### ISSUE THREAD

**Issue by orange2458** [Woon-2/cpp-study#132]
![image](https://user-images.githubusercontent.com/75879925/204320229-57cff16c-7402-4708-a532-72995002e5bd.png)
오류가 생겼습니다

**Comment by Woon-2** [comment]
홀리, 아마 `vector`로 실행했을 때 에러가 발생했겠군요.

`std::getline`은 `std::vector`를 받는 `overloading`이 없으니...

코드를 수정한 뒤 `PR` 하겠습니다.

p.s. `issue`에 `label`을 붙여주세용.   
오류 메시지 창 내용도 있으면 좋겠어요.    

[Work Tips](https://github.com/Woon-2/cpp-study/blob/main/docs/work_tips.md#%EC%BD%94%EB%93%9C-%EC%B2%A8%EB%B6%80-%ED%8C%81)

위 게시글 중 코드 첨부 팁 항목을 보시면,   
코드를 올리는 방법도 나와있습니다.

제가 작성한 #32 를 참고하세요.   

`Issue` 양식을 나중에 따로 만들 예정이어서,    
그때가면 양식을 따르는 것으로 귀찮음이 좀 덜해질 겁니다.
