### ISSUE TITLE
Do003 - 오타

### ISSUE THREAD

**Issue by Lcat12345** [Woon-2/cpp-study#137]
https://github.com/Woon-2/cpp-study/blob/b2bf6f3c4c016c6c6a42ebb49d4de9dd06565909/assignment-sprint1-write-cpp-classes/3.go%20for%20reference.md?plain=1#L344-L345

불가피한 순간이 -> 불가피한 순간에

**Comment by Woon-2** [comment]
롸?

'오다'를 '다가오다'로 생각하고 다시 읽어봐주세용

**Comment by Lcat12345** [comment]
넹면
