### ISSUE TITLE
Do004. 멤버 함수 선언 과제 수정

### ISSUE THREAD

**Issue by Woon-2** [Woon-2/cpp-study#138]
## Issue Description
`my_string`의 `replace` 함수의 설명이 바뀌었습니다.   
다른 구현이 필요해지므로, 멤버 함수 선언 과제를 위한 코드를 작성하셨다면 참고하여 수정해주시기 바랍니다.

## Issue Context
`assignments`의   
94c17d99cf87173bb02efa4198fc74b2f48c1560 - `refactoring` `Commit`에 대한 `Issue`입니다.
#45 의 '22.12.04. 스크럼에서 말씀드렸던 내용입니다.

두 분 다 확인하셨다고 댓글 달아주시면 `Issue`를 닫겠습니다.

**Comment by Lcat12345** [comment]
fde7960016b7c0227d7a95f55e38f652e26b5b22

수정했습니다.

**Comment by orange2458** [comment]
확인했습니다,  수정하도록 할게욤.

**Comment by Woon-2** [comment]
스프린트 종료
