### ISSUE TITLE
En004. 코드 중복을 줄이는 것이 좋습니다.

### ISSUE THREAD

**Issue by Woon-2** [Woon-2/cpp-study#139]
## Issue Description
`code`에서 공통된 성격을 가진 `data`와 `operation`들이 반복된다면,   
`function`이나 `class`로 `abstract`하는 것이 좋습니다.

과제에서 요구하는 건 최소한의 요구치입니다.    
좋은 `code`를 위해 몇 가지 `function`이나 `class`를 더 추가하셔도 괜찮습니다.

파레토 법칙이 프로그래밍에 응용되어

>런타임의 80%를 잡아먹는 코드는 전체 코드의 20%밖에 되지 않는다.    

라는 관용 표현이 많이 쓰이는데요.   
자잘한 성능에 신경쓰는 것보다 런타임 성능에 실제로 영향을 끼치는   
20%의 `code`를 찾아내는 것이 중요하다는 의미입니다.

## Issue Context
`Jongjin's-studyroom`의   
b54f2efef7f8a3d0c1a784b1bc7d546818653292 - `CS-1 CS-391 CS-396 레퍼런스 반환 과제` `Commit`에 대한 `Issue`입니다.

https://github.com/Woon-2/cpp-study/blob/b54f2efef7f8a3d0c1a784b1bc7d546818653292/assignment-sprint1-write-cpp-classes/assignment/Project1/go_for_reference.cpp#L27-L36

https://github.com/Woon-2/cpp-study/blob/b54f2efef7f8a3d0c1a784b1bc7d546818653292/assignment-sprint1-write-cpp-classes/assignment/Project1/go_for_reference.cpp#L38-L47

https://github.com/Woon-2/cpp-study/blob/b54f2efef7f8a3d0c1a784b1bc7d546818653292/assignment-sprint1-write-cpp-classes/assignment/Project1/go_for_reference.cpp#L49-L81

## Enhancement

```cpp
int sum(TestScore& ts)
{
    return ts.math + ts.english + ts.physics + ts.chemicals;
}
```

```cpp
TestScore& min(TestScore& lhs, TestScore& rhs)
{
    if (sum(lhs) < sum(rhs))
        return lhs;
    else
        return rhs;
}
```

```cpp
TestScore& max(TestScore& lhs, TestScore& rhs)
{
    if (&min(lhs, rhs) == &lhs)    // 파레토 법칙을 참고해,
        return rhs;               // 몇 개의 연산을 늘리는 대신
    else                          // 구현상의 코드 중복을 제거했습니다.
        return lhs;               // 추상화 수준이 가장 비슷한 함수를 이용하도록 합니다.
}
```

```cpp
TestScore& median_of_three(TestScore& one, TestScore& two, TestScore& three)
{
    int one_sum = sum(one);
    int two_sum = sum(two);
    int three_sum = sum(three);

    // 이하 기존과 동일
    
    // ...

    // 여기도 파레토 법칙을 참고하면
    // return min(max(one, two), max(two, three)); 의 한 줄로 끝낼 수도 있습니다.
}
```

**Comment by Lcat12345** [comment]
assignment-sprint1-write-cpp-classes/assignment/Project1/go_for_reference.cpp
