### ISSUE TITLE
En005. 함수의 선언에서 함수의 동작을 유추할 수 있어야 합니다.

### ISSUE THREAD

**Issue by Woon-2** [Woon-2/cpp-study#140]
## Issue Description
제가 과제에서 `function parameter`들을 n, m, k, l 따위로 표현하긴 했으나,   
여러분이 실제로 작성한 `parameter`의 이름은 설명적이어야 합니다.   

일반적으로 `variable`이 쓰이는 범위가 클수록   
더 길고 정확하게 그 `variable`의 역할을 설명하는 이름이 필요합니다. (_Code Complete 2_, Steve McConnell, 11.1)

`function parameter`는 보통 `function` 전체에 걸쳐서 쓰입니다.     
`code`에서의 물리적 `access` 말고도   
사용자가 해당 `function`이 무슨 일을 하는지 유추할 때에   
우리의 눈에 의해서 심리적으로도 `access`되죠.

그것을 감안해 n, m, k, l 따위의 이름은 피하도록 합시다.    
이 논지의 내용을 해당 과제에 추가토록 하겠습니다.

## Issue Context
`Jongjin's-studyroom`의   
fde7960016b7c0227d7a95f55e38f652e26b5b22 - `CS-1 CS-119 CS-222 replace 함수의 parameter를 수정` `Commit`에 대한 `Issue`,

https://github.com/Woon-2/cpp-study/blob/fde7960016b7c0227d7a95f55e38f652e26b5b22/assignment-sprint1-write-cpp-classes/assignment/Project1/my_string.h#L9-L29

`Sanghoon's-studyroom`의
2898e9f68f19e4212d2c6caccd466f40c1cdab8b - `CS-1 CS-187` `Commit`에 대한 `Issue`입니다.

https://github.com/Woon-2/cpp-study/blob/03370b01fb0ed872f91c6d39198b2243b2fce73f/New%20Project/New%20Project/my_string.h#L9-L30

## Enhancement

- n, m, k, l 등의 `parameter` 이름을 더 설명적이도록 수정합니다.
- `function declaration`에 `parameter`의 이름을 적지 않았다면, 적도록 합니다.

## Reference

Steve McConnell, 『Code Complete 2』, 서우석 옮김, (위키북스, 2020)
Robert C. Martin, 『Clean Code』, 박재호, 이해영 옮김, (인사이트, 2013)

**Comment by orange2458** [comment]
확인했습니다, 수정하도록 할게욤.

**Comment by Woon-2** [comment]
스프린트 종료
