### ISSUE TITLE
5th assignment 오타

### ISSUE THREAD

**Issue by Lcat12345** [Woon-2/cpp-study#71]
[7d280ee](https://github.com/Woon-2/cpp-study/commit/7d280eec57840e56f9951150642c680b3f7e0bfe) 

## 오타
https://github.com/Woon-2/cpp-study/blob/7d280eec57840e56f9951150642c680b3f7e0bfe/assignment-sprint1-write-cpp-classes/5.declare%20member%20variables.md#L8
또른 -> 또는

**Comment by Woon-2** [comment]
아니 이거 왜 안 닫히냐

**Comment by Lcat12345** [comment]
나 이제 코드 인용 좀 잘하는 듯
