### ISSUE TITLE
Do002 - 멤버 함수 선언 과제 수정

### ISSUE THREAD

**Issue by Woon-2** [Woon-2/cpp-study#81]
## Issue Description
`my_unique_ptr`의 `release` 함수의 설명이 바뀌었습니다.   
다른 구현이 필요해지므로, 멤버 함수 선언 과제를 위한 코드를 작성하셨다면 참고하여 수정해주시기 바랍니다.

## Issue Context
`assignments`의   
f0d707d7de49c56571006960f95e6075fdfa434b - `fixed description of my_unique_ptr<T>::release()` `Commit`에 대한 `Issue`입니다.

두 분 다 확인하셨다고 댓글 달아주시면 `Issue`를 닫겠습니다.

**Comment by Lcat12345** [comment]
ok

**Comment by orange2458** [comment]
Checked
